# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0024_auto_20170327_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfundingpostproposal',
            name='state',
            field=models.CharField(choices=[(b'DT', b'Draft'), (b'CD', b'Closed'), (b'RJ', b'Rejection')], default=b'DT', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalcrowdfundingpostproposal',
            name='state',
            field=models.CharField(choices=[(b'DT', b'Draft'), (b'CD', b'Closed'), (b'RJ', b'Rejection')], default=b'DT', max_length=2),
        ),
    ]
